### ISSUE TITLE
Provide Maven build

### ISSUE THREAD

**Issue by lschuetze** [jeantessier/dependency-finder#1]
I am currently using `mvn install:install-file -Dfile=<unzip-location>/lib/DependencyFinder.jar -DgroupId=net.sf.depfind -DartifactId=depfind -Dversion=1.2.1-beta4 -Dpackaging=jar` to install depfind into my local maven repository to be used as dependency with maven projects.

I am porting [gueryframework](https://github.com/lschuetze/gueryframework) to maven to be used in my thesis and its using your library as dependency. On SourceForge their are still >40 downloads per week. Maybe this could increase your audience.

Is there any interest into providing a maven build script and publish the library on Maven Central?

**Comment by rajatjain1996** [comment]
@jeantessier Any update on this?

**Comment by lschuetze** [comment]
Sorry, no. Feel free to reopen and contribute on your own. There was little time during the thesis and afterwards I was changing my scope.
